[common]
debug = false
netherTop = 127
noEnergy = false
convertDeepslateOres = false
[power]
rebornEnergyConversionCoefficient = 0.0625
fastTransferEnergyConversionCoefficient = 0.0625
creativeGeneratorGeneration = 1000
[quarry]
quarryEnergyCapacity = 10000.0
quarryEnergyMakeFrame = 50.0
quarryEnergyBreakBlock = 25.0
quarryEnergyRemoveFluid = 50.0
quarryEnergyMoveHead = 5.0
[adv_pump]
advPumpEnergyCapacity = 1000.0
advPumpEnergyRemoveFluid = 20.0
[adv_quarry]
advQuarryEnergyCapacity = 50000.0
advQuarryEnergyMakeFrame = 15.0
advQuarryEnergyBreakBlock = 10.0
advQuarryEnergyRemoveFluid = 50.0
advQuarryEnergyMoveHead = 25.0
