[xpCost]
inverseXpCost = false
blocksPerXpLevel = 650
minimumBaseXpCost = 0.0
maximumBaseXpCost = 3.0
xpCostPerLeashed = 1
dimensionalWarpXpCost = 5
globalWaystoneXpCostMultiplier = 1.0
warpStoneXpCostMultiplier = 1.0
waystoneXpCostMultiplier = 1.0
sharestoneXpCostMultiplier = 1.0
portstoneXpCostMultiplier = 1.0
warpPlateXpCostMultiplier = 1.0
inventoryButtonXpCostMultiplier = 2.0
[restrictions]
restrictToCreative = false
restrictRenameToOwner = true
generatedWaystonesUnbreakable = false
transportLeashed = true
transportLeashedDimensional = true
leashedDenyList = ["minecraft:wither"]
dimensionalWarp = "ALLOW"
dimensionalWarpAllowList = []
dimensionalWarpDenyList = []
allowWaystoneToWaystoneTeleport = true
globalWaystoneSetupRequiresCreativeMode = true
[cooldowns]
globalWaystoneCooldownMultiplier = 1.0
warpStoneCooldown = 300
warpStoneUseTime = 32
warpPlateUseTime = 20
scrollUseTime = 32
inventoryButtonCooldown = 1200
[inventoryButton]
inventoryButton = "NEAREST"
warpButtonX = 58
warpButtonY = 8
creativeWarpButtonX = 88
creativeWarpButtonY = 6
[worldGen]
worldGenStyle = "BIOME"
frequency = 0
dimensionAllowList = []
dimensionDenyList = ["minecraft:overworld", "minecraft:the_nether", "minecraft:the_end"]
nameGenerationMode = "PRESET_FIRST"
customWaystoneNames = []
spawnInVillages = true
forceSpawnInVillages = false
[client]
disableTextGlow = false
disableParticles = false
[compatibility]
displayWaystonesOnJourneyMap = true
