[graveSettings]
generateGraves = true
retrievalType = "ON_USE"
dropType = "IN_INVENTORY"
dropPlayerHead = false
dropGraveBlock = false
requireGraveItem = false
generateEmptyGraves = false
ignoreSpawnProtection = true
deathInSpawnProtection = "CREATE_GRAVE"
priority = "GRAVE"
unlockableGraves = true
deleteEnchantments = ["minecraft:vanishing_curse", "vanishing_curse"]
soulboundEnchantments = ["yigd:soulbound"]
voidSlots = []
soulboundSlots = []
applyBindingCurse = true
trySoft = false
tryStrict = true
replaceWhenClaimed = true
blacklistDimensions = []
graveInVoid = true
ignoreDeathTypes = []
graveSpawnHeight = 2
lastResort = "DROP_ITEMS"
putXpInGrave = true
defaultXpDrop = true
xpDropPercent = 50
tellDeathPos = false
maxGraveBackups = 50

[graveSettings.graveRobbing]
enableRobbing = true
onlyMurderer = false
afterTime = 1
timeType = "HOURS"
robPriority = "INVENTORY"

[graveSettings.graveDeletion]
canDelete = false
afterTime = 1
timeType = "HOURS"
dropInventory = false

[graveSettings.itemLoss]
enableLoss = false
ignoreSoulboundItems = true
affectStacks = false
usePercentRange = false
lossRangeFrom = 0
lossRangeTo = 5
percentChanceOfLoss = 100

[graveSettings.blockUnderGrave]
generateBlockUnder = true
inOverWorld = "twigs:rocky_dirt"
inNether = "minecraft:soul_soil"
inTheEnd = "minecraft:end_stone"
inCustom = "minecraft:dirt"

[graveSettings.graveCompatConfig]
levelzXpInGraves = true
levelzXpDropPercent = 100
claimRuleOverride = "CREATE_GRAVE"

[graveSettings.graveRenderSettings]
useRenderFeatures = true
renderGraveSkull = false
renderGraveOwner = true
textShadow = true
adaptRenderer = true
glowingGrave = true
glowMinDistance = 0
glowMaxDistance = 30
[utilitySettings.soulboundEnchant]
enabled = true
isTreasure = false
villagerTrade = true
tableAndLoot = false
[utilitySettings.deathSightEnchant]
enabled = false
isTreasure = true
villagerTrade = true
tableAndLoot = true
[utilitySettings.scrollItem]
scrollType = "DISABLED"
retrieveOnRespawn = true
[utilitySettings.graveKeySettings]
enableKeys = false
alwaysRequire = false
retrieveOnRespawn = true
getFromGui = false
rebindable = false
graveKeySpecification = "PLAYER"
[commandToggles]
coreCommandName = "yigd"
retrieveGrave = true
robGrave = true
selfView = true
adminView = true
moderateGraves = true
clearGraveBackups = true
whitelist = true
whitelistAdd = true
whitelistRemove = true
whitelistToggle = true
